/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.toedter.calendar.JCalendar;
import domainmodel.HoaDon;
import domainmodel.KhuyenMai;
import java.math.BigDecimal;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.IHoaDonService;
import service.impl.HoaDonService;
import viewmodel.GioHang;
import viewmodel.bangSPinHoaDon;
import viewmodel.HoaDonChiTiet;

/**
 *
 * @author HP probook
 */
public class FrmBanHang extends javax.swing.JFrame {

    /**
     * Creates new form banhang
     */
    public FrmBanHang() {
        initComponents();
        dtmSP = (DefaultTableModel) tblSP.getModel();
        listSP = hoaDonService.getSP();
        dtmGH = (DefaultTableModel) tblGH.getModel();
        listGH = hoaDonService.getGH();
        dtmHDCT = (DefaultTableModel) tblHoaDon.getModel();
        listHDCT = hoaDonService.getHD();
        listKM = hoaDonService.getKM();
        cbxKM.setModel(new DefaultComboBoxModel(listKM.toArray()));

        loadHDCT();
        loadSP();
        loadGH();

        setLocationRelativeTo(null);
    }
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultTableModel dtmSP = new DefaultTableModel();
    private DefaultTableModel dtmHDCT = new DefaultTableModel();
    private DefaultTableModel dtmGH = new DefaultTableModel();
    private DefaultComboBoxModel boxModel = new DefaultComboBoxModel();

    private IHoaDonService hoaDonService = new HoaDonService();
    List<bangSPinHoaDon> listSP = new ArrayList<>();
    List<HoaDonChiTiet> listHDCT = new ArrayList<>();
    List<GioHang> listGH = new ArrayList<>();
    List<KhuyenMai> listKM = new ArrayList<>();

    public void loadSP() {
        dtmSP.setRowCount(0);
        dtmSP = (DefaultTableModel) tblSP.getModel();
        listSP = hoaDonService.getSP();
        for (bangSPinHoaDon s : listSP) {
            dtmSP.addRow(new Object[]{s.getMaSP(), s.getTenSP(), s.getHang(), s.getMauSac(), s.getSize(),
                s.getGia(), s.getSoLuong(), s.getMoTa()});
        }
    }

    public void loadGH() {
        dtmGH.setRowCount(0);
        dtmGH = (DefaultTableModel) tblGH.getModel();
        listGH = hoaDonService.getGH();
        for (GioHang s : listGH) {
            dtmGH.addRow(new Object[]{s.getTenSP(), s.getHang(), s.getMauSac(),
                s.getSize(), s.getSoLuong(), s.getGia()
            });
        }
    }

    public void loadHDCT() {
        dtmHDCT.setRowCount(0);
        dtmHDCT = (DefaultTableModel) tblHoaDon.getModel();
        listHDCT = hoaDonService.getHD();
        for (HoaDonChiTiet s : listHDCT) {
            dtmHDCT.addRow(new Object[]{s.getMaHD(), s.getTenKH(), s.getTenSP(), s.getSl(), s.getMaNV(),
                s.getNgayTao(), s.getTongTien(), s.getTienCanTra(), s.getTienKhachDua(),
                s.getTIenThua(), s.TrangThai()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        ngaytao = new com.toedter.calendar.JDateChooser();
        txtTongTien = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        txtTienKD = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        txtTienCanTra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnChoTT = new javax.swing.JButton();
        cbxKM = new javax.swing.JComboBox<>();
        txtTienGiam = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGH = new javax.swing.JTable();
        btnBoSP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnTaoGh = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);

        jPanel8.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn"));

        jLabel7.setText("MaHD");

        jLabel12.setText("NgayTao");

        jLabel13.setText("TongTien");

        jLabel14.setText("SDT");

        jLabel15.setText("GhiChu");

        jLabel16.setText("TenKH");

        jLabel17.setText("MaKM");

        jLabel18.setText("MaNV");

        txtTongTien.setEditable(false);

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });

        txtTienKD.setText("0");
        txtTienKD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKDActionPerformed(evt);
            }
        });

        jLabel1.setText("Tiền KD");

        jLabel2.setText("Tiền thừa");

        btnHuy.setText("Hủy thanh toán");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        txtTienCanTra.setEditable(false);

        jLabel3.setText("Tiền cần trả");

        btnChoTT.setText("Thanh toán chờ");
        btnChoTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoTTActionPerformed(evt);
            }
        });

        cbxKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khuyến Mãi", "Item 2", "Item 3", "Item 4" }));
        cbxKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKMActionPerformed(evt);
            }
        });

        txtTienGiam.setText("0");
        txtTienGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienGiamActionPerformed(evt);
            }
        });

        jLabel4.setText("Tiền giảm");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel13))
                                            .addGap(18, 18, 18)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtTienKD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtTienCanTra)
                                                    .addComponent(txtTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                                                .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel2))))
                                .addGap(82, 88, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(btnThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnChoTT)))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel8Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel17))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                    .addGap(225, 225, 225)
                                    .addComponent(jLabel18)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHuy)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaNV, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtGhiChu, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtSDT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(txtTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(cbxKM, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTienGiam))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18)))
                .addGap(15, 15, 15)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(ngaytao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbxKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTienCanTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtTenKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienKD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel14)
                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTienThua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel15)
                    .addComponent(txtGhiChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChoTT)
                    .addComponent(btnHuy)
                    .addComponent(btnThanhToan))
                .addGap(30, 30, 30))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblGH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TÊN SP", "HÃNG", "MÀU SẮC", "SIZE", "SL", "GIÁ"
            }
        ));
        jScrollPane2.setViewportView(tblGH);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 140));

        btnBoSP.setText("Bỏ SP");
        btnBoSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoSPActionPerformed(evt);
            }
        });
        jPanel3.add(btnBoSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 80, -1));

        jButton1.setText("Sửa SL");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 80, -1));

        btnTaoGh.setText("Tạo GH");
        btnTaoGh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoGhActionPerformed(evt);
            }
        });
        jPanel3.add(btnTaoGh, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 80, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ SP", "TÊN SP", "HÃNG", "MÀU SẮC", "SIZE", "ĐƠN GIÁ", "SỐ LƯỢNG", "MÔ TẢ"
            }
        ));
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblSP);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1020, 170));

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "TÊN KH", "TÊN SP", "SL", "MANV", "NGÀY TẠO", "TỔNG TIỀN", "CẦN TRẢ", "KHÁCH ĐƯA", "TIỀN THỪA", "TRẠNG THÁI"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Hóa đơn chi tiết");

        jCheckBox2.setText("Đã TT");

        jCheckBox3.setText("Chờ TT");

        jCheckBox4.setText("Tất cả");

        jButton2.setText("Tìm MaHD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jCheckBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(223, 223, 223))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 189, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    HoaDonChiTiet ThongTinHD() {
        HoaDonChiTiet h = new HoaDonChiTiet();
        h.setMaHD(txtMaHD.getText());
        h.setNgayTao(ngaytao.getDate());
        h.setTongTien(Double.valueOf(txtTongTien.getText()));
        h.setSDT(txtSDT.getText());
        h.setTenKH(txtTenKH.getText());
        h.setMaKM(cbxKM.getSelectedItem().toString());
        h.setTienCanTra(Double.valueOf(txtTienCanTra.getText()));
        h.setTienKhachDua(Double.valueOf(txtTienKD.getText()));
        h.setTIenThua(Double.valueOf(txtTienThua.getText()));
        h.setTienCanTra(Double.valueOf(txtTienCanTra.getText()));
        h.setTrangThai(TrangThai());
        h.setMaNV(txtMaNV.getText());

        listHDCT.add(h);
        return h;
    }

    public int TrangThai() {

        try {
            int tk = Integer.parseInt(txtTienKD.getText());
            int tct = Integer.parseInt(txtTienCanTra.getText());
            if (tk < tct) {
                return 2;
            } else {
                return 1;
            }
        } catch (Exception e) {
            return 0;
        }
    }

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        double tkd = Double.valueOf(txtTienKD.getText());
        double tct = Double.valueOf(txtTienCanTra.getText());
        if (tkd < tct) {
            JOptionPane.showMessageDialog(this, "Không đủ tiền để thanh toán");
        } else {
            hoaDonService.Themhd(ThongTinHD());
            for (GioHang g : listGH) {
                hoaDonService.Themhdct(g.getTenSP(), txtMaHD.getText(), g.getSoLuong());
            }
            loadGH();
            loadHDCT();
            hoaDonService.bttaoGH();
        }

    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        // TODO add your handling code here:

        int i = tblSP.getSelectedRow();
        int sl = Integer.parseInt(tblSP.getValueAt(i, 6).toString());
        if (sl > 0) {
            int t = 0;
            hoaDonService.ClickSpVaoHd(tblSP.getValueAt(i, 0).toString());
            loadGH();
            loadSP();
            for (GioHang h : listGH) {
                t = (int) (t + h.getGia());
            }
            float tiengiam = Float.valueOf(txtTienGiam.getText());
            float tienct = t - tiengiam;
            txtTongTien.setText(String.valueOf(t));
            txtSDT.setText("0342215469");
            txtGhiChu.setText("ko");
            txtMaNV.setText("nv1");
            txtTenKH.setText("hung");
            txtTienCanTra.setText(String.valueOf(tienct));
            // float tienKD = Float.valueOf(txtTienKD.getText());
            // float tienThua = tienKD - tienct;
            // txtTienThua.setText(String.valueOf(tienThua));
            JCalendar jcalendar=new JCalendar();
            ngaytao.setDate(jcalendar.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "SP đã hết cửa hàng sẽ cập nhật thêm trong thời gian tới ");
        }
    }//GEN-LAST:event_tblSPMouseClicked

    private void btnChoTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoTTActionPerformed
        // TODO add your handling code here:
        hoaDonService.ThanhToanCho(Double.valueOf(txtTienKD.getText()), Double.valueOf(txtTienThua.getText()), txtMaHD.getText());
//        for (GioHang g : listGH) {
//            hoaDonService.Themhdct(g.getTenSP(), txtMaHD.getText(), g.getSoLuong());
//        }
        loadGH();
        loadHDCT();
        hoaDonService.bttaoGH();
    }//GEN-LAST:event_btnChoTTActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        for (GioHang g : listGH) {
            hoaDonService.HuyHD(g.getTenSP(), g.getSoLuong());
        }
        hoaDonService.bttaoGH();
        loadSP();
        loadGH();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void cbxKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKMActionPerformed
        // TODO add your handling code here:
//        for (int i = 0; i < listKM.size(); i++) {
//            if ((cbxKM.getSelectedItem() == listKM.get(i).getMaKM())) {
//                txtTienGiam.setText(String.valueOf(listKM.get(i).getSoTienGiam()));
//                System.out.println(listKM.get(i).getMaKM());
//            }
//        }
        KhuyenMai km = (KhuyenMai) cbxKM.getSelectedItem();
        hoaDonService.getKMsoTienGiam(km.getMaKM());
        txtTienGiam.setText(String.valueOf(km.getSoTienGiam()));
        int t = 0;
        for (GioHang h : listGH) {
            t = (int) (t + h.getGia());
        }
        float tiengiam = Float.valueOf(txtTienGiam.getText());
        float tienct = t - tiengiam;
        txtTongTien.setText(String.valueOf(t));

        txtTienCanTra.setText(String.valueOf(tienct));
        float tienKD = Float.valueOf(txtTienKD.getText());
        float tienThua = tienKD - tienct;
        txtTienThua.setText(String.valueOf(tienThua));
    }//GEN-LAST:event_cbxKMActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int i = tblHoaDon.getSelectedRow();
        txtMaHD.setText(tblHoaDon.getValueAt(i, 0).toString());
        ngaytao.setDate((Date) tblHoaDon.getValueAt(i, 5));
        txtTenKH.setText(tblHoaDon.getValueAt(i, 1).toString());
        // txtMaNV.setText(tblHoaDon.getValueAt(i, 4).toString());
        // cbxKM.setSelectedItem(tblHoaDon.getValueAt(i,4).toString());
        txtTongTien.setText(tblHoaDon.getValueAt(i, 6).toString());
        txtTienCanTra.setText(tblHoaDon.getValueAt(i, 7).toString());
        txtTienKD.setText(tblHoaDon.getValueAt(i, 8).toString());
        txtTienThua.setText(tblHoaDon.getValueAt(i, 9).toString());

        dtmGH = (DefaultTableModel) tblGH.getModel();
        listGH = hoaDonService.ClickHd(tblHoaDon.getValueAt(i, 0).toString());

        dtmGH.setRowCount(0);
        for (GioHang s : listGH) {
            dtmGH.addRow(new Object[]{s.getTenSP(), s.getHang(), s.getMauSac(),
                s.getSize(), s.getSoLuong(), s.getGia()
            });
        }


    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void txtTienKDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKDActionPerformed
        // TODO add your handling code here:
        int t = 0;
        for (GioHang h : listGH) {
            t = (int) (t + h.getGia());
        }
        float tiengiam = Float.valueOf(txtTienGiam.getText());
        float tienct = t - tiengiam;
        txtTongTien.setText(String.valueOf(t));
        txtSDT.setText("0342215469");
        txtGhiChu.setText("ko");
        txtMaNV.setText("nv1");
        txtTenKH.setText("hung");
        txtTienCanTra.setText(String.valueOf(tienct));
        float tienKD = Float.valueOf(txtTienKD.getText());
        float tienThua = tienKD - tienct;
        txtTienThua.setText(String.valueOf(tienThua));
    }//GEN-LAST:event_txtTienKDActionPerformed

    private void txtTienGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienGiamActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtTienGiamActionPerformed

    private void btnBoSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoSPActionPerformed
        // TODO add your handling code here:
        int i = tblGH.getSelectedRow();
        hoaDonService.xoaSPkhoiGH(tblGH.getValueAt(i, 0).toString(), Integer.parseInt(tblGH.getValueAt(i, 4).toString()));
        loadGH();
        loadSP();
    }//GEN-LAST:event_btnBoSPActionPerformed

    private void btnTaoGhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoGhActionPerformed
        // TODO add your handling code here:
        hoaDonService.bttaoGH();
        for (GioHang g : listGH) {
            hoaDonService.HuyHD(g.getTenSP(), g.getSoLuong());
        }
        hoaDonService.bttaoGH();
        loadGH();
        loadSP();
    }//GEN-LAST:event_btnTaoGhActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBanHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBanHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoSP;
    private javax.swing.JButton btnChoTT;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTaoGh;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cbxKM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser ngaytao;
    private javax.swing.JTable tblGH;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSP;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienCanTra;
    private javax.swing.JTextField txtTienGiam;
    private javax.swing.JTextField txtTienKD;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables
}
