/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.Timer;
import com.toedter.calendar.JCalendar;
import domainmodel.HoaDon;
import domainmodel.KhuyenMai;
import java.awt.Color;
import java.math.BigDecimal;
import java.util.AbstractList;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.IHoaDonService;
import service.impl.HoaDonService;
import viewmodel.GioHang;
import viewmodel.bangSPinHoaDon;
import viewmodel.HoaDonChiTiet;
/**
 *
 * @author Admin
 */
public class FrmHome extends javax.swing.JFrame {

    /**
     * Creates new form FrmHome
     */
    Timer timer;

    public FrmHome() {
        initComponents();
        dtmSP = (DefaultTableModel) tblSP.getModel();
        listSP = hoaDonService.getSP();
        dtmGH = (DefaultTableModel) tblGH.getModel();
        listGH = hoaDonService.getGH();
        dtmHDCT = (DefaultTableModel) tblHoaDon.getModel();
        listHDCT = hoaDonService.getHD();
        listKM = hoaDonService.getKM();
        cbxKM.setModel(new DefaultComboBoxModel(listKM.toArray()));

        loadHDCT();
        loadSP();
        loadGH();

        setLocationRelativeTo(null);
    }
    
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultTableModel dtmSP = new DefaultTableModel();
    private DefaultTableModel dtmHDCT = new DefaultTableModel();
    private DefaultTableModel dtmGH = new DefaultTableModel();
    private DefaultComboBoxModel boxModel = new DefaultComboBoxModel();

    private IHoaDonService hoaDonService = new HoaDonService();
    List<bangSPinHoaDon> listSP = new ArrayList<>();
    List<HoaDonChiTiet> listHDCT = new ArrayList<>();
    List<GioHang> listGH = new ArrayList<>();
    List<KhuyenMai> listKM = new ArrayList<>();

    public void loadSP() {
        dtmSP.setRowCount(0);
        dtmSP = (DefaultTableModel) tblSP.getModel();
        listSP = hoaDonService.getSP();
        for (bangSPinHoaDon s : listSP) {
            dtmSP.addRow(new Object[]{s.getMaSP(), s.getTenSP(), s.getHang(), s.getMauSac(), s.getSize(),
                s.getGia(), s.getSoLuong(), s.getMoTa()});
        }
    }

    public void loadGH() {
        dtmGH.setRowCount(0);
        dtmGH = (DefaultTableModel) tblGH.getModel();
        listGH = hoaDonService.getGH();
        for (GioHang s : listGH) {
            dtmGH.addRow(new Object[]{s.getTenSP(), s.getHang(), s.getMauSac(),
                s.getSize(), s.getSoLuong(), s.getGia()
            });
        }
    }

    public void loadHDCT() {
        dtmHDCT.setRowCount(0);
        dtmHDCT = (DefaultTableModel) tblHoaDon.getModel();
        listHDCT = hoaDonService.getHD();
        for (HoaDonChiTiet s : listHDCT) {
            dtmHDCT.addRow(new Object[]{s.getMaHD(), s.getTenKH(), s.getTenSP(), s.getSl(), s.getMaNV(),
                s.getNgayTao(), s.getTongTien(), s.getTienCanTra(), s.getTienKhachDua(),
                s.getTIenThua(), s.TrangThai()
            });
        }
    }
    
    HoaDonChiTiet ThongTinHD() {
        HoaDonChiTiet h = new HoaDonChiTiet();
        h.setMaHD(txtMaHD.getText());
        h.setNgayTao(ngaytao.getDate());
        h.setTongTien(Double.valueOf(txtTongTien.getText()));
        h.setSDT(txtSDT.getText());
        h.setTenKH(txtTenKH.getText());
        h.setMaKM(cbxKM.getSelectedItem().toString());
        h.setTienCanTra(Double.valueOf(txtTienCanTra.getText()));
        h.setTienKhachDua(Double.valueOf(txtTienKD.getText()));
        h.setTIenThua(Double.valueOf(txtTienThua.getText()));
        h.setTienCanTra(Double.valueOf(txtTienCanTra.getText()));
        h.setTrangThai(TrangThai());
        h.setMaNV(txtMaNV.getText());

        listHDCT.add(h);
        return h;
    }

    public int TrangThai() {

        try {
            int tk = Integer.parseInt(txtTienKD.getText());
            int tct = Integer.parseInt(txtTienCanTra.getText());
            if (tk < tct) {
                return 2;
            } else {
                return 1;
            }
        } catch (Exception e) {
            return 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        ngaytao = new com.toedter.calendar.JDateChooser();
        txtTongTien = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtMaNV = new javax.swing.JTextField();
        btnThanhToan = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        txtTienKD = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtTienThua = new javax.swing.JTextField();
        btnHuy = new javax.swing.JButton();
        txtTienCanTra = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        btnChoTT = new javax.swing.JButton();
        cbxKM = new javax.swing.JComboBox<>();
        txtTienGiam = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblGH = new javax.swing.JTable();
        btnBoSP = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnTaoGh = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSP = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phầm mềm bán giày");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 168, 133));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn"));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("MaHD");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 34, -1, -1));

        jLabel16.setText("NgayTao");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 68, -1, -1));

        jLabel17.setText("TongTien");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 111, -1, -1));

        jLabel18.setText("SDT");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 191, -1, -1));

        jLabel19.setText("GhiChu");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 231, -1, -1));

        jLabel20.setText("TenKH");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 151, -1, -1));

        jLabel21.setText("MaKM");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 71, -1, -1));

        jLabel22.setText("MaNV");
        jPanel9.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 34, -1, -1));
        jPanel9.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 31, 100, -1));
        jPanel9.add(ngaytao, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 68, 100, -1));

        txtTongTien.setEditable(false);
        jPanel9.add(txtTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 108, 100, -1));
        jPanel9.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 188, 100, -1));
        jPanel9.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 31, 100, -1));

        btnThanhToan.setText("Thanh toán");
        btnThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhToanActionPerformed(evt);
            }
        });
        jPanel9.add(btnThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 319, 115, -1));
        jPanel9.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 148, 100, -1));
        jPanel9.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 228, 100, -1));

        txtTienKD.setText("0");
        txtTienKD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienKDActionPerformed(evt);
            }
        });
        jPanel9.add(txtTienKD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 188, 100, -1));

        jLabel4.setText("Tiền KD");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 191, 50, -1));

        jLabel23.setText("Tiền thừa");
        jPanel9.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 231, -1, -1));
        jPanel9.add(txtTienThua, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 228, 100, -1));

        btnHuy.setText("Hủy thanh toán");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });
        jPanel9.add(btnHuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(296, 319, -1, -1));

        txtTienCanTra.setEditable(false);
        jPanel9.add(txtTienCanTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 148, 100, -1));

        jLabel24.setText("Tiền cần trả");
        jPanel9.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 154, 67, -1));

        btnChoTT.setText("Thanh toán chờ");
        btnChoTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChoTTActionPerformed(evt);
            }
        });
        jPanel9.add(btnChoTT, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 319, -1, -1));

        cbxKM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khuyến Mãi", "Item 2", "Item 3", "Item 4" }));
        cbxKM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKMActionPerformed(evt);
            }
        });
        jPanel9.add(cbxKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 68, 100, -1));

        txtTienGiam.setText("0");
        txtTienGiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienGiamActionPerformed(evt);
            }
        });
        jPanel9.add(txtTienGiam, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 108, 100, -1));

        jLabel25.setText("Tiền giảm");
        jPanel9.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 111, -1, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 420, 380));

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giỏ Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblGH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "TÊN SP", "HÃNG", "MÀU SẮC", "SIZE", "SL", "GIÁ"
            }
        ));
        jScrollPane2.setViewportView(tblGH);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 600, 140));

        btnBoSP.setText("Bỏ SP");
        btnBoSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBoSPActionPerformed(evt);
            }
        });
        jPanel11.add(btnBoSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 80, -1));

        jButton1.setText("Sửa SL");
        jPanel11.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 80, -1));

        btnTaoGh.setText("Tạo GH");
        btnTaoGh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoGhActionPerformed(evt);
            }
        });
        jPanel11.add(btnTaoGh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 80, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 620, 210));

        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã HD", "TÊN KH", "TÊN SP", "SL", "MANV", "NGÀY TẠO", "TỔNG TIỀN", "CẦN TRẢ", "KHÁCH ĐƯA", "TIỀN THỪA", "TRẠNG THÁI"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel12.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 32, 624, 122));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setText("Hóa đơn chi tiết");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 4, -1, -1));

        jCheckBox2.setText("Đã TT");
        jPanel12.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 5, 85, -1));

        jCheckBox3.setText("Chờ TT");
        jPanel12.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 5, 85, -1));

        jCheckBox4.setText("Tất cả");
        jPanel12.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 5, 85, -1));
        jPanel12.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(413, 4, 111, -1));

        jButton2.setText("Tìm MaHD");
        jPanel12.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 4, -1, -1));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ SP", "TÊN SP", "HÃNG", "MÀU SẮC", "SIZE", "ĐƠN GIÁ", "SỐ LƯỢNG", "MÔ TẢ"
            }
        ));
        tblSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSPMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblSP);

        jPanel13.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 1020, 170));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 0, 1090, 680));

        jPanel2.setBackground(new java.awt.Color(248, 210, 155));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 60));

        jPanel3.setBackground(new java.awt.Color(239, 168, 133));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel3.setPreferredSize(new java.awt.Dimension(120, 42));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-shopping-cart-32.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bán Hàng");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 150, 50));

        jPanel4.setBackground(new java.awt.Color(248, 230, 200));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 196, 255)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel5.setText("Log Out");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-logout-rounded-32.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 150, 50));

        jPanel6.setBackground(new java.awt.Color(248, 230, 200));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel6MousePressed(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel9.setText("Sản Phẩm");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hg.png"))); // NOI18N
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 150, 50));

        jPanel5.setBackground(new java.awt.Color(248, 230, 200));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel7.setText("Sản Phẩm");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hg.png"))); // NOI18N
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 150, 50));

        jPanel7.setBackground(new java.awt.Color(248, 230, 200));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel11.setText("Sản Phẩm");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hg.png"))); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 150, 50));

        jPanel8.setBackground(new java.awt.Color(248, 230, 200));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 196, 255)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 13)); // NOI18N
        jLabel13.setText("Sản Phẩm");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 70, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/hg.png"))); // NOI18N
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        jPanel2.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 150, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
//        FrmLogin frmSanPham = new FrmLogin();
//        frmSanPham.show();
//        this.dispose();
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin();
        frmLogin.show();
        this.dispose();
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel3MouseClicked

    private void btnThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhToanActionPerformed
        double tkd = Double.valueOf(txtTienKD.getText());
        double tct = Double.valueOf(txtTienCanTra.getText());
        if (tkd < tct) {
            JOptionPane.showMessageDialog(this, "Không đủ tiền để thanh toán");
        } else {
            hoaDonService.Themhd(ThongTinHD());
            for (GioHang g : listGH) {
                hoaDonService.Themhdct(g.getTenSP(), txtMaHD.getText(), g.getSoLuong());
            }
            loadGH();
            loadHDCT();
            hoaDonService.bttaoGH();
        }
    }//GEN-LAST:event_btnThanhToanActionPerformed

    private void txtTienKDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienKDActionPerformed
        // TODO add your handling code here:
        int t = 0;
        for (GioHang h : listGH) {
            t = (int) (t + h.getGia());
        }
        float tiengiam = Float.valueOf(txtTienGiam.getText());
        float tienct = t - tiengiam;
        txtTongTien.setText(String.valueOf(t));
        txtSDT.setText("0342215469");
        txtGhiChu.setText("ko");
        txtMaNV.setText("nv1");
        txtTenKH.setText("hung");
        txtTienCanTra.setText(String.valueOf(tienct));
        float tienKD = Float.valueOf(txtTienKD.getText());
        float tienThua = tienKD - tienct;
        txtTienThua.setText(String.valueOf(tienThua));
    }//GEN-LAST:event_txtTienKDActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
        for (GioHang g : listGH) {
            hoaDonService.HuyHD(g.getTenSP(), g.getSoLuong());
        }
        hoaDonService.bttaoGH();
        loadSP();
        loadGH();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void btnChoTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChoTTActionPerformed
        // TODO add your handling code here:
        hoaDonService.ThanhToanCho(Double.valueOf(txtTienKD.getText()), Double.valueOf(txtTienThua.getText()), txtMaHD.getText());
        //        for (GioHang g : listGH) {
            //            hoaDonService.Themhdct(g.getTenSP(), txtMaHD.getText(), g.getSoLuong());
            //        }
        loadGH();
        loadHDCT();
        hoaDonService.bttaoGH();
    }//GEN-LAST:event_btnChoTTActionPerformed

    private void cbxKMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKMActionPerformed
        // TODO add your handling code here:
        //        for (int i = 0; i < listKM.size(); i++) {
            //            if ((cbxKM.getSelectedItem() == listKM.get(i).getMaKM())) {
                //                txtTienGiam.setText(String.valueOf(listKM.get(i).getSoTienGiam()));
                //                System.out.println(listKM.get(i).getMaKM());
                //            }
            //        }
        KhuyenMai km = (KhuyenMai) cbxKM.getSelectedItem();
        hoaDonService.getKMsoTienGiam(km.getMaKM());
        txtTienGiam.setText(String.valueOf(km.getSoTienGiam()));
        int t = 0;
        for (GioHang h : listGH) {
            t = (int) (t + h.getGia());
        }
        float tiengiam = Float.valueOf(txtTienGiam.getText());
        float tienct = t - tiengiam;
        txtTongTien.setText(String.valueOf(t));

        txtTienCanTra.setText(String.valueOf(tienct));
        float tienKD = Float.valueOf(txtTienKD.getText());
        float tienThua = tienKD - tienct;
        txtTienThua.setText(String.valueOf(tienThua));
    }//GEN-LAST:event_cbxKMActionPerformed

    private void txtTienGiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienGiamActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTienGiamActionPerformed

    private void btnBoSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBoSPActionPerformed
        // TODO add your handling code here:
        int i = tblGH.getSelectedRow();
        hoaDonService.xoaSPkhoiGH(tblGH.getValueAt(i, 0).toString(), Integer.parseInt(tblGH.getValueAt(i, 4).toString()));
        loadGH();
        loadSP();
    }//GEN-LAST:event_btnBoSPActionPerformed

    private void btnTaoGhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoGhActionPerformed
        // TODO add your handling code here:
        hoaDonService.bttaoGH();
        for (GioHang g : listGH) {
            hoaDonService.HuyHD(g.getTenSP(), g.getSoLuong());
        }
        hoaDonService.bttaoGH();
        loadGH();
        loadSP();
    }//GEN-LAST:event_btnTaoGhActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        int i = tblHoaDon.getSelectedRow();
        txtMaHD.setText(tblHoaDon.getValueAt(i, 0).toString());
        ngaytao.setDate((Date) tblHoaDon.getValueAt(i, 5));
        txtTenKH.setText(tblHoaDon.getValueAt(i, 1).toString());
        // txtMaNV.setText(tblHoaDon.getValueAt(i, 4).toString());
        // cbxKM.setSelectedItem(tblHoaDon.getValueAt(i,4).toString());
        txtTongTien.setText(tblHoaDon.getValueAt(i, 6).toString());
        txtTienCanTra.setText(tblHoaDon.getValueAt(i, 7).toString());
        txtTienKD.setText(tblHoaDon.getValueAt(i, 8).toString());
        txtTienThua.setText(tblHoaDon.getValueAt(i, 9).toString());

        dtmGH = (DefaultTableModel) tblGH.getModel();
        listGH = hoaDonService.ClickHd(tblHoaDon.getValueAt(i, 0).toString());

        dtmGH.setRowCount(0);
        for (GioHang s : listGH) {
            dtmGH.addRow(new Object[]{s.getTenSP(), s.getHang(), s.getMauSac(),
                s.getSize(), s.getSoLuong(), s.getGia()
            });
        }

    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void tblSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSPMouseClicked
        // TODO add your handling code here:

        int i = tblSP.getSelectedRow();
        int sl = Integer.parseInt(tblSP.getValueAt(i, 6).toString());
        if (sl > 0) {
            int t = 0;
            hoaDonService.ClickSpVaoHd(tblSP.getValueAt(i, 0).toString());
            loadGH();
            loadSP();
            for (GioHang h : listGH) {
                t = (int) (t + h.getGia());
            }
            float tiengiam = Float.valueOf(txtTienGiam.getText());
            float tienct = t - tiengiam;
            txtTongTien.setText(String.valueOf(t));
            txtSDT.setText("0342215469");
            txtGhiChu.setText("ko");
            txtMaNV.setText("nv1");
            txtTenKH.setText("hung");
            txtTienCanTra.setText(String.valueOf(tienct));
            // float tienKD = Float.valueOf(txtTienKD.getText());
            // float tienThua = tienKD - tienct;
            // txtTienThua.setText(String.valueOf(tienThua));
            JCalendar jcalendar=new JCalendar();
            ngaytao.setDate(jcalendar.getDate());
        } else {
            JOptionPane.showMessageDialog(this, "SP đã hết cửa hàng sẽ cập nhật thêm trong thời gian tới ");
        }
    }//GEN-LAST:event_tblSPMouseClicked

    private void jPanel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MousePressed
        // TODO add your handling code here:
        setBackground(Color.BLUE);
    }//GEN-LAST:event_jPanel6MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FrmHome().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBoSP;
    private javax.swing.JButton btnChoTT;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnTaoGh;
    private javax.swing.JButton btnThanhToan;
    private javax.swing.JComboBox<String> cbxKM;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private com.toedter.calendar.JDateChooser ngaytao;
    private javax.swing.JTable tblGH;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblSP;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenKH;
    private javax.swing.JTextField txtTienCanTra;
    private javax.swing.JTextField txtTienGiam;
    private javax.swing.JTextField txtTienKD;
    private javax.swing.JTextField txtTienThua;
    private javax.swing.JTextField txtTongTien;
    // End of variables declaration//GEN-END:variables

}
