/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import com.toedter.calendar.JCalendar;
import domainmodel.KhuyenMai;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repository.KhuyenMaiRepository;
import service.impl.KhuyenMaiServiceImpl;
import service.IKhuyenMaiService;

/**
 *
 * @author AS
 */
public class FrmKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form FrmKhuyenMai
     */
    private DefaultTableModel defaultTableModel;
    private ButtonGroup buttonGroup;
    List<KhuyenMai> list = new ArrayList<>();
    IKhuyenMaiService khuyenMaiService = new KhuyenMaiServiceImpl();
    KhuyenMaiRepository khuyenMaiRepository = new KhuyenMaiRepository();

    public FrmKhuyenMai() {
        initComponents();
        buttonGroupTrangThai();
        list=khuyenMaiService.getAll();
        loadData(khuyenMaiService.getAll());
        jobCheckKM();
        
    }

    public void buttonGroupTrangThai() {
        buttonGroup = new ButtonGroup();
        buttonGroup.add(rdTrangThai_tatca);
        buttonGroup.add(rdTrangThai_dangdienra);
        buttonGroup.add(rdTrangThai_sapdienra);
        buttonGroup.add(rdTrangThai_hethan);
    }

    public void loadData(List<KhuyenMai> list) {
        defaultTableModel = (DefaultTableModel) tbKhuyenMai.getModel();
        defaultTableModel.setRowCount(0);

        for (KhuyenMai khuyenMai : list) {

            String trangThai = null;
            if (khuyenMai.getTrangThai() == 0) {
                trangThai = "Ngừng HD";
            } else if (khuyenMai.getTrangThai() == 1) {
                trangThai = "Đang diễn ra";
            } else {
                trangThai = "Sắp diễn ra";
            }

            defaultTableModel.addRow(new Object[]{
                khuyenMai.getMaKM(),
                khuyenMai.getTenKM(),
                khuyenMai.getSoTienGiam(),
                khuyenMai.getNgayBD(),
                khuyenMai.getNgayKT(),
                trangThai
            //khuyenMai.getTrangThai() //<1<2:"Hết hạn","Đang diễn ra","Sắp diễn ra"
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rdTrangThai_tatca = new javax.swing.JRadioButton();
        rdTrangThai_dangdienra = new javax.swing.JRadioButton();
        rdTrangThai_sapdienra = new javax.swing.JRadioButton();
        rdTrangThai_hethan = new javax.swing.JRadioButton();
        btnMoi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        dateNgayBD = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTenKM = new javax.swing.JTextField();
        txtSoTienGiam = new javax.swing.JTextField();
        dateNgayKT = new com.toedter.calendar.JDateChooser();
        lblTenKM = new javax.swing.JLabel();
        lblMaKM = new javax.swing.JLabel();
        lblSoTienGiam = new javax.swing.JLabel();
        lblnbd = new javax.swing.JLabel();
        lblNkt = new javax.swing.JLabel();
        txtMaKM = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbKhuyenMai = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setBackground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Trạng thái");

        rdTrangThai_tatca.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdTrangThai_tatca.setText("Tất cả");
        rdTrangThai_tatca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdTrangThai_tatcaMouseClicked(evt);
            }
        });

        rdTrangThai_dangdienra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdTrangThai_dangdienra.setText("Đang diễn ra");
        rdTrangThai_dangdienra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdTrangThai_dangdienraMouseClicked(evt);
            }
        });
        rdTrangThai_dangdienra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTrangThai_dangdienraActionPerformed(evt);
            }
        });

        rdTrangThai_sapdienra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdTrangThai_sapdienra.setText("Sắp diễn ra");
        rdTrangThai_sapdienra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdTrangThai_sapdienraMouseClicked(evt);
            }
        });

        rdTrangThai_hethan.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        rdTrangThai_hethan.setText("Ngừng HD");
        rdTrangThai_hethan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdTrangThai_hethanMouseClicked(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rdTrangThai_hethan)
                            .addComponent(rdTrangThai_dangdienra)
                            .addComponent(rdTrangThai_tatca)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rdTrangThai_sapdienra))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(rdTrangThai_tatca)
                .addGap(18, 18, 18)
                .addComponent(rdTrangThai_dangdienra)
                .addGap(18, 18, 18)
                .addComponent(rdTrangThai_sapdienra)
                .addGap(18, 18, 18)
                .addComponent(rdTrangThai_hethan)
                .addGap(44, 44, 44)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Mã khuyến mãi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Số tiền giảm");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Tên khuyến mãi");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Ngày bắt đầu");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Ngày kết thúc");

        lblTenKM.setText("*");

        lblSoTienGiam.setText("*");

        lblnbd.setText("*");

        lblNkt.setText("*");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblMaKM)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMaKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(109, 109, 109)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblnbd)
                                            .addComponent(dateNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNkt)
                                            .addComponent(dateNgayKT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(66, 66, 66))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTenKM)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTenKM, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(txtSoTienGiam))
                            .addComponent(lblSoTienGiam))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(dateNgayBD, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(txtMaKM)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaKM)
                    .addComponent(lblnbd))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenKM, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(dateNgayKT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenKM)
                    .addComponent(lblNkt))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtSoTienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(lblSoTienGiam))
        );

        tbKhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khuyến mãi", "Tên khuyến mãi", "Số tiền giảm", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ));
        tbKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbKhuyenMai);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Ngừng HD");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(186, 186, 186)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
    }// </editor-fold>//GEN-END:initComponents
    public boolean check() {

     
        if (txtTenKM.getText().isBlank() == true) {
            lblTenKM.setText("Không bỏ trống mục *.");

        } else {
            lblTenKM.setText("");

        }
        if (txtSoTienGiam.getText().isBlank() == true) {
            lblSoTienGiam.setText("Không bỏ trống mục *.");

        } else {
            lblSoTienGiam.setText("");

        }
        if (dateNgayBD.getDate() == null) {
            lblnbd.setText("Không bỏ trống mục *");
        } else {
            lblnbd.setText("");

        }
        if (dateNgayKT.getDate() != null) {
            lblNkt.setText("");
        } else {
            lblNkt.setText("Không bỏ trống mục *");
            return false;

        }

        return true;
    }

    public boolean checkngay() {
        JCalendar jcalendar = new JCalendar();
        if (dateNgayBD.getDate().compareTo(dateNgayKT.getDate()) > 0) {
            lblnbd.setText("Ngày bắt đầu không được lớn hơn ngày kết thúc *.");
            return false;
        } else {
            lblnbd.setText("");

        }
        if (dateNgayKT.getDate().compareTo(jcalendar.getDate()) <= 0) {
            lblNkt.setText("Ngày kết thúc không được bé hơn ngày hiện tại *.");
            return false;
        } else {
            lblNkt.setText("");

        }
        return true;
    }

    private void jobCheckKM() {
        JCalendar jcalendar = new JCalendar();
        int i = tbKhuyenMai.getSelectedRow();
        new Thread() {

            @Override
            public void run() {
              

                while (true) {
                    List<KhuyenMai> lstKM = khuyenMaiRepository.getAll();
                    for (KhuyenMai s : lstKM) {
//                        int resultBD = LocalDate.now().compareTo(s.getNgayBD().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
//                        int resultKT = LocalDate.now().compareTo(s.getNgayKT().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());

                        if (s.getNgayBD().compareTo(jcalendar.getDate()) > 0) {
                            khuyenMaiRepository.updateTT(2, s.getMaKM());

                        } else {
                            if (s.getNgayKT().compareTo(jcalendar.getDate()) <= 0) {
                                khuyenMaiRepository.updateTT(0, s.getMaKM());
                            } else {
                                khuyenMaiRepository.updateTT(1, s.getMaKM());
                            }
                        }
                         // loadData(khuyenMaiService.getAll());

                    }
                    try {
                        Thread.sleep(1000);
                    } catch (Exception e) {
                    }
                }
            }
        }.start();
        loadData(khuyenMaiService.getAll());
    }
      public String taoMa() {
        int i = list.size() + 1;
        txtMaKM.setText("KM" + i);
        return null;
    }

 
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
       taoMa();
        if (check() && checkngay()) {

            KhuyenMai km = new KhuyenMai();
            km.setMaKM(txtMaKM.getText());
            km.setTenKM(txtTenKM.getText());
            km.setSoTienGiam(new Double(txtSoTienGiam.getText()));
            km.setNgayBD(dateNgayBD.getDate());
            km.setNgayKT(dateNgayKT.getDate());

            khuyenMaiService.add(km);
            JOptionPane.showMessageDialog(this, "Thêm thành công!");
            loadData(khuyenMaiService.getAll());
        }
         list=khuyenMaiService.getAll();

    }//GEN-LAST:event_btnThemActionPerformed


    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        if (check() && checkngay()) {
            int row = tbKhuyenMai.getSelectedRow();
            if (row == -1) {
                JOptionPane.showMessageDialog(this, "Chọn mã cần sửa.");
            } else {
                KhuyenMai km = new KhuyenMai();

                km.setMaKM(txtMaKM.getText());
                km.setTenKM(txtTenKM.getText());
                km.setSoTienGiam(new Double(txtSoTienGiam.getText()));
                km.setNgayBD(dateNgayBD.getDate());
                km.setNgayKT(dateNgayKT.getDate());
                //  km.setTrangThai(Integer.parseInt(txtTrangThai.getText()));
//            if (cbxTT.getSelectedItem().equals("Đang diễn ra")) {
//                km.setTrangThai(1);
//            } else if (cbxTT.getSelectedItem().equals("Hết hạn")) {
//                km.setTrangThai(0);
//            } else {
//                km.setTrangThai(2);
//            }

                khuyenMaiService.update(km);
                loadData(khuyenMaiService.getAll());
                JOptionPane.showMessageDialog(this, "Sửa thành công!");
            }
        }


    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int i = tbKhuyenMai.getSelectedRow();
        KhuyenMai khuyenMai = new KhuyenMai();
        khuyenMai.setTrangThai(0);

        KhuyenMaiRepository kmr = new KhuyenMaiRepository();
        kmr.ngungHD(khuyenMai, tbKhuyenMai.getValueAt(i, 0).toString());
        JOptionPane.showMessageDialog(this, "Cập nhật thành công");
        loadData(khuyenMaiService.getAll());
    }//GEN-LAST:event_btnXoaActionPerformed

    private void rdTrangThai_tatcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdTrangThai_tatcaMouseClicked
        // TODO add your handling code here:
        loadData(khuyenMaiService.getAll());
    }//GEN-LAST:event_rdTrangThai_tatcaMouseClicked

    private void rdTrangThai_dangdienraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdTrangThai_dangdienraMouseClicked
        // TODO add your handling code here:
        loadData(khuyenMaiService.dangDienRa());
    }//GEN-LAST:event_rdTrangThai_dangdienraMouseClicked

    private void rdTrangThai_sapdienraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdTrangThai_sapdienraMouseClicked
        // TODO add your handling code here:
        loadData(khuyenMaiService.sapDienRa());
    }//GEN-LAST:event_rdTrangThai_sapdienraMouseClicked

    private void rdTrangThai_hethanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdTrangThai_hethanMouseClicked
        // TODO add your handling code here:
        loadData(khuyenMaiService.hetHan());
    }//GEN-LAST:event_rdTrangThai_hethanMouseClicked

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        txtMaKM.setText("");
        txtSoTienGiam.setText("");
        txtTenKM.setText("");

        txtMaKM.setText("");

    }//GEN-LAST:event_btnMoiActionPerformed

    private void rdTrangThai_dangdienraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTrangThai_dangdienraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdTrangThai_dangdienraActionPerformed

    private void tbKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKhuyenMaiMouseClicked
        // TODO add your handling code here:
        List<KhuyenMai> km = new ArrayList<>();
        int row = tbKhuyenMai.getSelectedRow();
        int trangThai;
        txtMaKM.setText((String) tbKhuyenMai.getValueAt(row, 0));
        txtTenKM.setText((String) tbKhuyenMai.getValueAt(row, 1));
        txtSoTienGiam.setText(String.valueOf(tbKhuyenMai.getValueAt(row, 2).toString()));
        dateNgayBD.setDate((Date) tbKhuyenMai.getValueAt(row, 3));
        dateNgayKT.setDate((Date) tbKhuyenMai.getValueAt(row, 4));
        //        if (tbKhuyenMai.getValueAt(row, 5).equals("Đang diễn ra")) {
            //            cbxTT.setSelectedItem("Đang diễn ra");
            //        } else if (tbKhuyenMai.getValueAt(row, 5).equals("Sắp diễn ra")) {
            //            cbxTT.setSelectedItem("Sắp diễn ra");
            //
            //        } else {
            //            cbxTT.setSelectedItem("Hết hạn");
            //
            //        }
        // txtTrangThai.setText(String.valueOf(trangThai));

    }//GEN-LAST:event_tbKhuyenMaiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private com.toedter.calendar.JDateChooser dateNgayBD;
    private com.toedter.calendar.JDateChooser dateNgayKT;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblMaKM;
    private javax.swing.JLabel lblNkt;
    private javax.swing.JLabel lblSoTienGiam;
    private javax.swing.JLabel lblTenKM;
    private javax.swing.JLabel lblnbd;
    private javax.swing.JRadioButton rdTrangThai_dangdienra;
    private javax.swing.JRadioButton rdTrangThai_hethan;
    private javax.swing.JRadioButton rdTrangThai_sapdienra;
    private javax.swing.JRadioButton rdTrangThai_tatca;
    private javax.swing.JTable tbKhuyenMai;
    private javax.swing.JLabel txtMaKM;
    private javax.swing.JTextField txtSoTienGiam;
    private javax.swing.JTextField txtTenKM;
    // End of variables declaration//GEN-END:variables
}
