/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import domainmodel.MauSac;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import service.MausacService;
import service.impl.MausacServiceimpl;

/**
 *
 * @author PC DUNG
 */
public class Mausacview extends javax.swing.JFrame {

    DefaultTableModel defaultTable = new DefaultTableModel();
    List<MauSac> listMausac = new ArrayList<>();
    MausacService mausacService = new MausacServiceimpl();

    /**
     * Creates new form Dongspview
     */
    public Mausacview() {
        initComponents();
        listMausac = mausacService.getListMausac();
        fillMausac();
    }

    public void fillMausac() {
        defaultTable.setRowCount(0);
        defaultTable = (DefaultTableModel) tblMausac.getModel();
        for (MauSac ms : listMausac) {
            defaultTable.addRow(new Object[]{ms.getId(), ms.getMa(), ms.getTen()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMausac = new javax.swing.JTable();
        btnDeleteMs = new javax.swing.JButton();
        btnUpdateMs = new javax.swing.JButton();
        btnSaveMs = new javax.swing.JButton();
        btnNewMs = new javax.swing.JButton();
        lblTendongsp = new javax.swing.JLabel();
        txtTenmausac = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMamausac = new javax.swing.JTextField();
        lblMadongsp = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIDmausac = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        tblMausac.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "MÃ", "TÊN"
            }
        ));
        tblMausac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMausacMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMausac);

        btnDeleteMs.setText("Delete");
        btnDeleteMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteMsActionPerformed(evt);
            }
        });

        btnUpdateMs.setText("Update");
        btnUpdateMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateMsActionPerformed(evt);
            }
        });

        btnSaveMs.setText("Save");
        btnSaveMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveMsActionPerformed(evt);
            }
        });

        btnNewMs.setText("New");
        btnNewMs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewMsActionPerformed(evt);
            }
        });

        lblTendongsp.setForeground(new java.awt.Color(255, 51, 51));
        lblTendongsp.setText("*");

        jLabel5.setText("Tên");

        lblMadongsp.setForeground(new java.awt.Color(255, 51, 51));
        lblMadongsp.setText("*");

        jLabel4.setText("Mã");

        txtIDmausac.setEditable(false);

        jLabel2.setText("ID");

        jLabel1.setText("Màu sắc");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(btnNewMs, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSaveMs, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnUpdateMs)
                            .addGap(34, 34, 34)
                            .addComponent(btnDeleteMs)
                            .addGap(48, 48, 48))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtTenmausac, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTendongsp, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtIDmausac, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblMadongsp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtMamausac, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE))))
                            .addContainerGap(48, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDmausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMamausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(lblMadongsp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenmausac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTendongsp)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteMs, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateMs, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaveMs, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNewMs, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean checkdieuKien() {
        if (txtMamausac.getText().isBlank()) {
            lblMadongsp.setText("Mã màu sắc còn trống");

        } else {
            lblMadongsp.setText("");
        }

        if (txtTenmausac.getText().isEmpty()) {
            lblTendongsp.setText("Tên màu sắc còn trống");
            return false;
        } else {
            lblTendongsp.setText("");
        }

        return true;
    }

    public boolean checkdkupdate() {

        if (txtTenmausac.getText().isEmpty()) {
            lblTendongsp.setText("Tên dòng sản phẩm còn trống");
            return false;
        } else {
            lblTendongsp.setText("");
        }

        return true;
    }

    private void btnNewMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewMsActionPerformed
        // TODO add your handling code here:
        txtIDmausac.setText("");
        txtMamausac.setText("");
        txtTenmausac.setText("");
    }//GEN-LAST:event_btnNewMsActionPerformed

    //check ma trung
    private boolean checkMatcher(List<MauSac> list, String Ma) {

        for (MauSac taikhoan : list) {
            if (taikhoan.getMa().equals(Ma)) {
                JOptionPane.showMessageDialog(this, "Mã màu đã tồn tại");
                return false;
            }
        }
        return true;
    }

    private void btnSaveMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveMsActionPerformed
        // TODO add your handling code here:
        if (checkdieuKien()) {
            MauSac dong = new MauSac();
            if (checkMatcher(listMausac, txtMamausac.getText())) {
                dong.setId(txtIDmausac.getText());
                dong.setMa(txtMamausac.getText());
                dong.setTen(txtTenmausac.getText());
                mausacService.add(dong);
                JOptionPane.showMessageDialog(this, "Thêm dòng sản phẩm thành công");

            }
            listMausac = mausacService.getListMausac();
            fillMausac();
    }//GEN-LAST:event_btnSaveMsActionPerformed
    }

    private void tblMausacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMausacMouseClicked
        // TODO add your handling code here:
        int index = tblMausac.getSelectedRow();
        txtIDmausac.setText(tblMausac.getValueAt(index, 0).toString());
        txtMamausac.setText(tblMausac.getValueAt(index, 1).toString());
        txtTenmausac.setText(tblMausac.getValueAt(index, 2).toString());
    }//GEN-LAST:event_tblMausacMouseClicked

    private void btnUpdateMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateMsActionPerformed
        // TODO add your handling code here:
        int index = tblMausac.getSelectedRow();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Chọn hàng để sửa");
        } else {

            MauSac ms = new MauSac();
            ms.setId(txtIDmausac.getText());
            ms.setMa(txtMamausac.getText());
            ms.setTen(txtTenmausac.getText());
            mausacService.update(ms);
            listMausac = mausacService.getListMausac();
            JOptionPane.showMessageDialog(this, "Cập nhập thành công");
            fillMausac();

        }
    }//GEN-LAST:event_btnUpdateMsActionPerformed

    private void btnDeleteMsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteMsActionPerformed
        // TODO add your handling code here:
        int row = tblMausac.getSelectedRow();
        int j = tblMausac.getSelectedRowCount() - 1;
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn hàng muốn xóa");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                //dongspService.delete(tblDongsp.getValueAt(row,0).toString());
                if (row >= 0) {
                    for (int i = row; i <= row + j; i++) {
                        MauSac d = new MauSac();
                        mausacService.delete(tblMausac.getValueAt(row, 0).toString());
                        JOptionPane.showMessageDialog(this, "Xóa thành công");
                        listMausac = mausacService.getListMausac();
                        fillMausac();
                    }

                }
            }
        }

    }//GEN-LAST:event_btnDeleteMsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mausacview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mausacview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mausacview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mausacview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mausacview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteMs;
    private javax.swing.JButton btnNewMs;
    private javax.swing.JButton btnSaveMs;
    private javax.swing.JButton btnUpdateMs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblMadongsp;
    private javax.swing.JLabel lblTendongsp;
    private javax.swing.JTable tblMausac;
    private javax.swing.JTextField txtIDmausac;
    private javax.swing.JTextField txtMamausac;
    private javax.swing.JTextField txtTenmausac;
    // End of variables declaration//GEN-END:variables
}
